const puppeteer = require('puppeteer');
const { writeFileSync, mkdirSync } = require('fs');
const { join } = require('path');

const COOKIES_DIR = process.env.COOKIES_DIR || '/data';
const COOKIES_FILE = join(COOKIES_DIR, 'cookies.txt');
const PROFILE_DIR = join(COOKIES_DIR, 'chrome-profile');

function log(msg) {
  console.log(`[${new Date().toISOString()}] ${msg}`);
}

async function main() {
  log('Starting cookie refresh...');

  mkdirSync(COOKIES_DIR, { recursive: true });

  const browser = await puppeteer.launch({
    headless: 'new',
    executablePath: process.env.CHROME_BIN || '/usr/bin/chromium',
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-gpu',
      '--window-size=1920,1080',
      '--proxy-server=socks5://xray:10808',
    ],
    userDataDir: PROFILE_DIR,
  });

  const page = await browser.newPage();
  await page.setUserAgent(
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
  );

  try {
    log('Navigating to YouTube...');
    await page.goto('https://www.youtube.com', {
      waitUntil: 'networkidle2',
      timeout: 30000,
    });

    await new Promise((r) => setTimeout(r, 5000));

    const cookies = await page.cookies('https://www.youtube.com', 'https://google.com');
    log(`Got ${cookies.length} cookies`);

    if (cookies.length === 0) {
      log('WARNING: No cookies obtained');
      await browser.close();
      process.exit(1);
    }

    let netscape = '# Netscape HTTP Cookie File\n';
    netscape += '# This file is generated by cookie-refresh. Do not edit.\n\n';

    for (const c of cookies) {
      const domain = c.domain.startsWith('.') ? c.domain : '.' + c.domain;
      const expiry = c.expires > 0 ? Math.floor(c.expires) : 0;
      const secure = c.secure ? 'TRUE' : 'FALSE';
      const httpOnly = c.httpOnly ? 'TRUE' : 'FALSE';
      netscape += `${domain}\tTRUE\t${c.path}\t${secure}\t${expiry}\t${c.name}\t${c.value}\n`;
    }

    writeFileSync(COOKIES_FILE, netscape);
    log(`Cookies saved to ${COOKIES_FILE} (${cookies.length} entries)`);
  } catch (e) {
    log(`Error: ${e.message}`);
  }

  await browser.close();
  log('Cookie refresh completed');
}

main().catch((e) => {
  log(`Fatal: ${e.message}`);
  process.exit(1);
});
