import asyncio
import json
import sys
from http.server import HTTPServer, BaseHTTPRequestHandler
from pathlib import Path
from threading import Thread

from playwright.async_api import async_playwright, BrowserContext

SESSION_DIR = Path("/data/session")
COOKIES_FILE = Path("/data/cookies.txt")
STATE_FILE = SESSION_DIR / "state.json"

REFRESH_INTERVAL = 30 * 60
LOGIN_URL = "https://accounts.google.com"
YOUTUBE_URL = "https://www.youtube.com"


def export_cookies_netscape(context: BrowserContext, output: Path) -> None:
    cookies = context.cookies()
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by cookie_provider. Do not edit.",
        "",
    ]
    for c in cookies:
        domain = c["domain"]
        if not domain.startswith("."):
            domain = "." + domain
        flag = "TRUE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = str(int(c.get("expires", 0)))
        name = c["name"]
        value = c["value"]
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")

    output.parent.mkdir(parents=True, exist_ok=True)
    tmp = output.with_suffix(".tmp")
    tmp.write_text("\n".join(lines) + "\n")
    tmp.rename(output)
    print(f"[cookie-provider] Exported {len(cookies)} cookies to {output}")


async def wait_for_login() -> None:
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context()
        page = await context.new_page()

        await page.goto(LOGIN_URL)
        print(f"[cookie-provider] Open browser and log in: {page.url}")
        print("[cookie-provider] Waiting for login... (check /data/login_url.txt)")

        url_file = Path("/data/login_url.txt")
        url_file.parent.mkdir(parents=True, exist_ok=True)
        url_file.write_text(page.url)

        while True:
            cookies = context.cookies()
            hasSID = any(c["name"] == "SID" for c in cookies)
            if hasSID:
                print("[cookie-provider] Login detected!")
                break
            await asyncio.sleep(2)

        SESSION_DIR.mkdir(parents=True, exist_ok=True)
        state = await context.storage_state()
        STATE_FILE.write_text(json.dumps(state))

        export_cookies_netscape(context, COOKIES_FILE)
        await context.close()
        await browser.close()


async def refresh_cookies() -> None:
    if not STATE_FILE.exists():
        print("[cookie-provider] No session found. Run 'login' first.")
        return

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context(storage_state=str(STATE_FILE))
        page = await context.new_page()

        try:
            await page.goto(YOUTUBE_URL, wait_until="domcontentloaded", timeout=30000)
            await asyncio.sleep(3)

            state = await context.storage_state()
            STATE_FILE.write_text(json.dumps(state))

            export_cookies_netscape(context, COOKIES_FILE)
            print("[cookie-provider] Cookies refreshed successfully")
        except Exception as e:
            print(f"[cookie-provider] Refresh error: {e}")
        finally:
            await context.close()
            await browser.close()


class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(b'{"status":"ok"}')

    def log_message(self, format, *args):
        pass


def start_health_server() -> None:
    server = HTTPServer(("0.0.0.0", 8080), HealthHandler)
    Thread(target=server.serve_forever, daemon=True).start()


async def run_service() -> None:
    start_health_server()
    print("[cookie-provider] Service started on port 8080")

    await refresh_cookies()

    while True:
        await asyncio.sleep(REFRESH_INTERVAL)
        await refresh_cookies()


def main() -> None:
    if len(sys.argv) > 1 and sys.argv[1] == "login":
        asyncio.run(wait_for_login())
    else:
        asyncio.run(run_service())


if __name__ == "__main__":
    main()
